package sql

import (
	"fmt"

	"github.com/88250/lute"
	"github.com/88250/lute/ast"
	"github.com/88250/lute/parse"
	"github.com/siyuan-note/siyuan/kernel/av"
	"github.com/siyuan-note/siyuan/kernel/filesys"
	"github.com/siyuan-note/siyuan/kernel/treenode"
	"github.com/siyuan-note/siyuan/kernel/util"
)

func RenderAttributeViewKanban(attrView *av.AttributeView, view *av.View, query string, depth *int, cachedAttrViews map[string]*av.AttributeView, ignoreRows bool) (ret *av.Kanban) {
	viewable := attrView.RenderedViewables[view.ID]
	if nil != viewable {
		ret = viewable.(*av.Kanban)
		return
	}

	ret = &av.Kanban{
		BaseInstance:           av.NewViewBaseInstance(view),
		CoverFrom:              view.Kanban.CoverFrom,
		CoverFromAssetKeyID:    view.Kanban.CoverFromAssetKeyID,
		CardAspectRatio:        view.Kanban.CardAspectRatio,
		CardSize:               view.Kanban.CardSize,
		FitImage:               view.Kanban.FitImage,
		DisplayFieldName:       view.Kanban.DisplayFieldName,
		FillColBackgroundColor: view.Kanban.FillColBackgroundColor,
		Fields:                 []*av.KanbanField{},
		Cards:                  []*av.KanbanCard{},
	}

	// Assemble the fields
	for _, field := range view.Kanban.Fields {
		key, getErr := attrView.GetKey(field.ID)
		if nil != getErr {
			// If the field can't be found, remove it from the view (a metadata-query scenario doesn't persist to disk)
			if !ignoreRows {
				removeMissingField(attrView, view, field.ID)
			}
			continue
		}

		ret.Fields = append(ret.Fields, &av.KanbanField{
			BaseInstanceField: &av.BaseInstanceField{
				ID:           key.ID,
				Name:         key.Name,
				Type:         key.Type,
				Icon:         key.Icon,
				Wrap:         field.Wrap,
				Hidden:       field.Hidden,
				Desc:         key.Desc,
				Calc:         field.Calc,
				Options:      key.Options,
				NumberFormat: key.NumberFormat,
				Template:     key.Template,
				Relation:     key.Relation,
				Rollup:       key.Rollup,
				Date:         key.Date,
				Created:      key.Created,
				Updated:      key.Updated,
			},
		})
	}

	// For scenarios like menus that only need field/view metadata, skip processing every card
	if ignoreRows {
		return
	}

	cardsValues := generateAttrViewItems(attrView, view) // Generate cards
	filterNotFoundAttrViewItems(cardsValues)             // Filter out cards that no longer exist

	// Batch-load the trees for bound blocks
	var ialIDs []string
	for _, keyValues := range cardsValues {
		for _, kValues := range keyValues {
			blockVal := kValues.GetBlockValue()
			if nil != blockVal && !blockVal.IsDetached {
				ialIDs = append(ialIDs, blockVal.Block.ID)
			}
		}
	}
	boundTrees := filesys.LoadTrees(ialIDs)

	// Generate the card field values
	for cardID, cardValues := range cardsValues {
		// Index by field ID, to avoid a linear lookup per field in the field loop below
		kvByField := map[string]*av.KeyValues{}
		for _, keyValues := range cardValues {
			if _, ok := kvByField[keyValues.Key.ID]; !ok { // When the same field has multiple values, only take the first
				kvByField[keyValues.Key.ID] = keyValues
			}
		}

		var kanbanCard av.KanbanCard
		for _, field := range ret.Fields {
			var fieldValue *av.KanbanFieldValue
			if keyValues, ok := kvByField[field.ID]; ok {
				fieldValue = &av.KanbanFieldValue{
					BaseValue: &av.BaseValue{
						ID:        keyValues.Values[0].ID,
						Value:     keyValues.Values[0],
						ValueType: field.Type,
					},
				}
			}
			if nil == fieldValue {
				fieldValue = &av.KanbanFieldValue{
					BaseValue: &av.BaseValue{
						ID:        cardID[:14] + ast.NewNodeID()[14:],
						ValueType: field.Type,
					},
				}
			}
			kanbanCard.ID = cardID

			filedDateIsTime := false
			if nil != field.Date {
				filedDateIsTime = field.Date.FillSpecificTime
			}
			fillAttributeViewBaseValue(fieldValue.BaseValue, field.ID, cardID, field.NumberFormat, field.Template, filedDateIsTime)
			kanbanCard.Values = append(kanbanCard.Values, fieldValue)
		}

		fillAttributeViewKanbanCardCover(attrView, view, cardValues, &kanbanCard, cardID, luteEngine, boundTrees)
		ret.Cards = append(ret.Cards, &kanbanCard)
	}

	// Backfill and complete the data
	fillAttributeViewKeyValues(attrView, ret)

	// Batch-fetch block attributes to improve performance
	ials := BatchGetBlockAttrsWitTrees(ialIDs, boundTrees)

	// Render auto-generated field values, such as relation, rollup, created time, and updated time
	fillAttributeViewAutoGeneratedValues(attrView, ret, ials, depth, cachedAttrViews)

	// Render template fields last, so templates can use the rollup, relation, created time, and updated time values
	renderTemplateErr := fillAttributeViewTemplateValues(attrView, view, ret, ials)
	if nil != renderTemplateErr {
		util.PushErrMsg(fmt.Sprintf(util.Langs[util.Lang][44], util.EscapeHTML(renderTemplateErr.Error())), 30000)
	}

	filterByQuery(query, ret)
	manualSort(view, ret)
	return
}

func fillAttributeViewKanbanCardCover(attrView *av.AttributeView, view *av.View, cardValues []*av.KeyValues, kanbanCard *av.KanbanCard, cardID string, luteEngine *lute.Lute, trees map[string]*parse.Tree) {
	switch view.Kanban.CoverFrom {
	case av.CoverFromNone:
	case av.CoverFromContentImage:
		blockValue := getBlockValue(cardValues)
		if blockValue.IsDetached {
			break
		}

		tree := trees[blockValue.Block.ID]
		if nil == tree {
			break
		}
		node := treenode.GetNodeInTree(tree, blockValue.Block.ID)
		if nil == node {
			break
		}

		if ast.NodeDocument == node.Type {
			if titleImg := treenode.GetDocTitleImgPath(node); "" != titleImg {
				kanbanCard.CoverURL = titleImg
				break
			}

			if titleImgCSS := node.IALAttr("title-img"); "" != titleImgCSS {
				kanbanCard.CoverURL = titleImgCSS
				break
			}
		}

		ast.Walk(node, func(n *ast.Node, entering bool) ast.WalkStatus {
			if !entering {
				return ast.WalkContinue
			}

			if ast.NodeImage != n.Type {
				return ast.WalkContinue
			}

			dest := n.ChildByType(ast.NodeLinkDest)
			if nil == dest {
				return ast.WalkContinue
			}
			kanbanCard.CoverURL = dest.TokensStr()
			return ast.WalkStop
		})

		if "" == kanbanCard.CoverURL {
			kanbanCard.CoverContent = renderCoverContentBlock(node, luteEngine)
			return
		}
	case av.CoverFromAssetField:
		if "" == view.Kanban.CoverFromAssetKeyID {
			break
		}

		assetValue := attrView.GetValue(view.Kanban.CoverFromAssetKeyID, cardID)
		if nil == assetValue || 1 > len(assetValue.MAsset) {
			break
		}

		for _, asset := range assetValue.MAsset {
			if asset.Type == av.AssetTypeImage && util.IsPossiblyImage(asset.Content) {
				kanbanCard.CoverURL = asset.Content
				break
			}
		}
		return
	case av.CoverFromContentBlock:
		blockValue := getBlockValue(cardValues)
		if blockValue.IsDetached {
			break
		}

		tree := trees[blockValue.Block.ID]
		if nil == tree {
			break
		}
		node := treenode.GetNodeInTree(tree, blockValue.Block.ID)
		if nil == node {
			break
		}
		kanbanCard.CoverContent = renderCoverContentBlock(node, luteEngine)
	}
}
